### PR TITLE
Subscription not removed when unsubscribing with EndpointOrientedTopology

### LINKED ISSUE #459: Unsubscribing from an event doesn't work with EndpointOrientedTopology
## Who's affected

- Anyone that requires to be able to unsubscribe endpoints from events and using `EndpointOrientedTopology`

## Symptoms

Unsubscribe requests are not persisted, causing unsubscribed endpoints continue receiving events after those endpoints were restarts.

## Details

Similar to the issue that was found in `ForwardingTopology` (#392).

The request to unsubscribe should be modifying topologies. [Currently](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e5f64e929ecf7ff2227541870ae9a2c243ed9222/src/Transport/Seam/SubscriptionManager.cs#L28) it doesn't.

For the `EndpointOrientedTopology`, subscriber should remove the subscription from the publisher.events topic.

This could cause events to accumulate under subscription that is no longer monitored. If there's a high volume of these events, subscription could eventually overflood and cause production degradation.

### PR DESCRIPTION
**Pull request by SeanFeldman**
## Who's affected

- Anyone that requires to be able to unsubscribe endpoints from events and using `EndpointOrientedTopology`

## Symptoms

Unsubscribe requests are not persisted, causing unsubscribed endpoints continue receiving events after those endpoints were restarts.

## Details

Similar to the issue that was found in `ForwardingTopology` (#392).

The request to unsubscribe should be modifying topologies. [Currently](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e5f64e929ecf7ff2227541870ae9a2c243ed9222/src/Transport/Seam/SubscriptionManager.cs#L28) it doesn't.

For the `EndpointOrientedTopology`, subscriber should remove the subscription from the publisher.events topic.

This could cause events to accumulate under subscription that is no longer monitored. If there's a high volume of these events, subscription could eventually overflood and cause production degradation.

#### TODO
- [ ] backport to `support-7.0`
- [ ] port changes to `develop`

@Particular/azure-maintainers please review

### CODE REVIEW

File: src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs [hunk 1]
```diff
@@ -39,15 +39,15 @@ public AzureServiceBusSubscriptionCreatorV6(ReadOnlySettings settings)
 
             var subscriptionDescription = new SubscriptionDescription(topicPath, subscriptionName);
             
-            // check the if the subscription with event name only is the one we should delete, i.e. event with another namespace owns it
-            if (!await SubscriptionIsReusedAcrossDifferentNamespaces(subscriptionDescription, sqlFilter, namespaceManager).ConfigureAwait(false))
+            // Check subscription with event name only is the one we should delete. If it's reused, then we need to use event full name.
+            if (await SubscriptionIsReusedAcrossDifferentNamespaces(subscriptionDescription, sqlFilter, namespaceManager).ConfigureAwait(false))
```
Comment (danielmarbach) [inline src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs]: Difficult to follow for me why we inverse the bool check

**Comment by danielmarbach** [comment]
According to our support policy I think we need to release a hotfix for 7.0.x as well, right?

File: src/AcceptanceTests/Routing/When_unsubscribing.cs [hunk 2]
```diff
@@ -0,0 +1,95 @@
...
+        {
+            var context = await Scenario.Define<Context>()
+                .WithEndpoint<Endpoint>(b => b.When((session, c) => session.Unsubscribe<MyEvent>()))
+                .Done(c => c.EndpointsStarted)
+                .Run();
+
+            var connectionString = Environment.GetEnvironmentVariable("AzureServiceBusTransport.ConnectionString");
+            var namespaceManager = NamespaceManager.CreateFromConnectionString(connectionString);
+
+            if (!context.IsForwardingTopology)
```
Comment (SeanFeldman) [inline src/AcceptanceTests/Routing/When_unsubscribing.cs]: Yeah, I realized that I didn't have anything after pushing, but by then needed to wrap up. Will add it second case as well, because it's actually more sophisticated (has 2 cases on its own).

File: src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs (hunk 1 above)
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusSubscriptionCreatorV6.cs]: If the was the same event from a different namespace, then the subscription entity we're interested in is using a full type name, rather than just a name. This was a bug. We did the inverse.

**Comment by SeanFeldman** [comment]
Correct. I've updated the general description to have that as an actionable item. `hotfix-7.0.5` branch is in place now and based on the outcomes of #461 will update it.

**Comment by SeanFeldman** [comment]
Update: both topologies are tested now. For `ForwardingTopology` all permutations are validated.

@Particular/azure-maintainers this is ready for final review.

**Comment by SeanFeldman** [comment]
@danielmarbach tried to avoid test execution for the 2nd topology by skipping it in the transport configuration, but ATTs doesn't allow it (throws).

**Comment by danielmarbach** [comment]
Hmm... that worked for me. Care to show me the code u used?

**Comment by SeanFeldman** [comment]
Haven't committed as it wasn't working, but it was the following code in `ConfigureEndpointAzureServiceBusTransport.cs`

```c#
if (endpointName == NameForEndpoint<When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.Endpoint>())
{
  Assert.Ignore("not applicable ...");
}
```

File: src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+            if (context.IsForwardingTopology)
+            {
+                var isSubscriptionFound = await namespaceManager.SubscriptionExistsAsync("bundle-1", endpointName);
+                Assert.IsTrue(isSubscriptionFound, "Subscription under 'bundle-1' should have been found, but it wasn't.");
+
+                isSubscriptionFound = await namespaceManager.SubscriptionExistsAsync("bundle-2", endpointName);
+                Assert.IsTrue(isSubscriptionFound, "Subscription under 'bundle-2' should have been found, but it wasn't.");
+
+                var rules = await namespaceManager.GetRulesAsync("bundle-1", endpointName);
+                Assert.That(rules.Any(rule => rule.Name == ruleName), Is.False);
```
Comment (Scooletz) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: I think I'd prefer to assert the content of the whole collection. Ensuring that one item does not exist seems to week to me.

File: src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+
+                rules = await namespaceManager.GetRulesAsync("bundle-2", endpointName);
+                Assert.That(rules.Any(rule => rule.Name == ruleName), Is.False);
```
Comment (Scooletz) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: Assert whole collection.

**Comment by Scooletz** [comment]
Beside assertion comment, LGTM.

File: src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs (hunk 3 above)
Comment (SeanFeldman) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: We only care for a specific event to be unsubscribed, therefore that one should not be found. The rest of the events - we shouldn't care about those.

File: src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs (hunk 4 above)
Comment (SeanFeldman) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: Same as [here](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/462#discussion_r93771549)

File: src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs (hunk 3 above)
Comment (Scooletz) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: I don't agree. We care for an event being unsubscribed AND the other left as it was.

Comment (SeanFeldman) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: Disagree. 
We've got another tests that verifies that a single event subscription will cause removal of the subscription and rule. In this scenario, we only care about specific event subscription. If there are other events (which we shouldn't care about) , then subscription won't be removed. In case subscription is not found (tested here), then we'll fail as should have.
We care for the specific event to be removed and for the subscription to remain if there are other events. We've got another test that verifies

Comment (SeanFeldman) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: I.e. for this scenario it is known that there will be _other subscriptions_, one or many shouldn't matter. What should matter is that 
1. The subscription for the event we've unsubscribed from is not found
1. Subscription entity remains (due to other event subscriptions still remaining)

Since there are only two events subscribed to, one of them no longer exists, but subscription entity is there, backed up with the 2nd test (`when_unsubscribing`) it defacto asserts that the second event subscription was not removed.

Comment (Scooletz) [inline src/AcceptanceTests/Routing/When_unsubscribing_from_one_of_the_events_for_ForwardingTopology.cs]: It's not about the other test testing a singular subscription case. The current assertion is an assertion against the action result (removal of the subscription). Turning that into the assertion against the state (how it looks after) would make it explicit.
The reasoning that if a subscription is there it must contain the other event is implicitly based on the other test. Making the assertion against the state makes this state explicitly based on the test itself.
As I'll be off, so please don't treat my comment as a blocker.

**Comment by SeanFeldman** [comment]
Assertion modified as per review request.
