### PR TITLE
Fix unsubscribe

### LINKED ISSUE #392: Unsubscribing from an event doesn't work
## Who's affected

- Anyone that requires to be able to unsubscribe endpoints from events

## Symptoms

Unsubscribe requests are not persisted, causing unsubscribed endpoints continue receiving events after those endpoints were restarts.

## Details

Issue raised based on the SO question [here](http://stackoverflow.com/questions/40249886/nservicebus-pub-sub-on-azure-service-bus-queues)

The request to unsubscribe should be modifying topologies. [Currently](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/e5f64e929ecf7ff2227541870ae9a2c243ed9222/src/Transport/Seam/SubscriptionManager.cs#L28) it doesn't.
For the `ForwardingTopology`, subscriber should remove the subscription rule from all the bundles/namespaces.
For the `EndpointOrientedTopology`, subscriber should remove the subscription from the publisher.events topic.

### PR DESCRIPTION
**Pull request by SeanFeldman**
Fixes #392

To implement unsubscribe functionality, 3 internal contracts were added to avoid public API changes (additions) which will be internalized in 7.1.0:

```diff
public interface ICreateTopologyAbleToDeleteSubscriptions
{
+  System.Threading.Tasks.Task TearDownSubscription(NServiceBus.Transport.AzureServiceBus.TopologySection topologySection);
}

public interface INamespaceManagerAbleToDeleteSubscriptions
{
+  DeleteSubscription(Microsoft.ServiceBus.Messaging.SubscriptionDescription subscriptionDescription);
}      

public interface ICreateAzureServiceBusSubscriptionsAbleToDeleteSubscriptions
{
+  System.Threading.Tasks.Task DeleteSubscription(string topicPath, string subscriptionName, NServiceBus.Transport.AzureServiceBus.SubscriptionMetadata metadata, string sqlFilter, NServiceBus.Transport.AzureServiceBus.INamespaceManager namespaceManager, string forwardTo);
}
```

~~According to SemVer, this should not be a hotfix, but a minor version. There's already a [PR targeting next minor](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/388) which discusses making these contracts internal. In addition, there's a [bug fix PR](https://github.com/Particular/NServiceBus.AzureServiceBus/pull/393) that was originally targeting  `hotfix-7.0.3`.~~

I suggest we first agree on #388 and based on that decide on the next steps.

### Related items are

- Bug fix for #391 (PR #393)
- Bug fix for #392 (this PR)
- Internalizing contracts #390 (PR #388)

**Update**: agreement was reached on #388.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers fyi

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers please review

File: src/Transport/Topology/TopologyCreator.cs [hunk 1]
```diff
@@ -51,5 +51,36 @@ public TopologyCreator(ITransportPartsContainer container, IManageNamespaceManag
                 }
             }
         }
+
+        public async Task TearDownSubscription(TopologySection topologySection)
```
Comment (yvesgoeleven) [inline src/Transport/Topology/TopologyCreator.cs]: Rename to teardown?

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 2]
```diff
@@ -135,6 +135,46 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
...
+                    if (await ExistsAsync(topicPath, subscriptionName, metadata.Description, namespaceManager, removeCacheEntry:true).ConfigureAwait(false))
+                    {
+                        var ruleDescription = new RuleDescription
+                        {
+                            Filter = new SqlFilter(sqlFilter),
+                            Name = metadata.SubscriptionNameBasedOnEventWithNamespace
+                        };
+                        logger.Info($"Removing subscription rule '{ruleDescription.Name}' for event '{meta.SubscribedEventFullName}'");
+                        var subscriptionClient = SubscriptionClient.CreateFromConnectionString(meta.NamespaceInfo.ConnectionString, topicPath, subscriptionName);
+                        await subscriptionClient.RemoveRuleAsync(ruleDescription.Name).ConfigureAwait(false);
```
Comment (yvesgoeleven) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: Consider removing the subscription entity if no forwarding rules are left

File: src/Transport/Topology/ICreateTopology.cs [hunk 3]
```diff
@@ -11,4 +11,10 @@ public interface ICreateTopology
     {
         Task Create(TopologySection topology);
     }
+
+    // TODO: Move into internalized ICreateTopology in v8
+    interface ICreateTopologyAbleToDeleteSubscriptions
```
Comment (SeanFeldman) [inline src/Transport/Topology/ICreateTopology.cs]: Rename to `ITearDownTopologySection`
