### PR TITLE
Hotfix 7.0.4

### LINKED ISSUE #429: Circuit breaker never invoked when messages are failing to be received
## Who's affected 

- Anyone using Azure Service Bus transport version 7 and up

## Symptoms

Circuit breaker is not triggered when messages are failing to be received.

## Details

[MessageReceiveNotifier](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Receiving/MessageReceiverNotifier.cs#L108) should invoke error callback when OnMessage API is failing to receive a message, which in turn should arm circuit breaker. `OnError` callback passed into `MessageReceiveNotifier` from `TopologyOperator`, but itself is [*never* assigned](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Topology/TopologyOperator.cs#L78). The original intent was to [assign `TopologyOperator` an error callback](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/796324278aa179eb0836eefbe977e5189488958a/src/Transport/Seam/MessagePump.cs#L91) that would trigger a circuit breaker arming in `MessagePump`, but the code is never exercised in `MessagePump.Init()`.

### PR DESCRIPTION
**Pull request by danielmarbach**
Fixes #429

### CODE REVIEW

**Comment by danielmarbach** [comment]
@Scooletz @tmasternak  here we go. Thanks for the awesome pairing and taking it on while I'm away

**Comment by danielmarbach** [comment]
@Scooletz @tmasternak can you please review. I applied additional cleanup. Decided to stay with AsyncAutoResetEvent since it was used in the other test in the file. Also applied code code cleanup as a sep. commit to the files we touched

**Comment by danielmarbach** [comment]
@Scooletz @tmasternak paired with awesome @boblangley on this one. We came to the conclusion that the initial intent of the test `Should_retry_after_rollback_in_less_then_thirty_seconds_when_using_via_queue` was actually the circuit breaker trigger interval and not the peek lock duration. The idea was to test whether another message receive on the pump marks the circuit breaker as successful before the circuit breaker trigger critical error action. Please have a look

File: src/Tests/Seam/When_dispatching_messages_in_receive_context.cs [hunk 1]
```diff
@@ -228,29 +231,23 @@ public class When_dispatching_messages_in_receive_context
...
                 {
-                    firstTime = DateTime.Now;
+                    stopWatch = Stopwatch.StartNew();
                 }
 
                 if (invocationCount == 2)
                 {
-                    secondTime = DateTime.Now;
-                    retried.Set();
+                    stopWatch?.Stop();
```
Comment (SeanFeldman) [inline src/Tests/Seam/When_dispatching_messages_in_receive_context.cs]: Is null coalesce necessary here?

File: src/Tests/Seam/When_dispatching_messages_in_receive_context.cs [hunk 2]
```diff
@@ -284,5 +216,34 @@ public class When_dispatching_messages_in_receive_context
...
             return sectionManager;
         }
+
+        void StartPumpWithConcurrencySetToOne()
+        {
+            // start the pump
+            pump.Start(new PushRuntimeSettings(1));
+        }
+
+        async Task StopPump()
```
Comment (SeanFeldman) [inline src/Tests/Seam/When_dispatching_messages_in_receive_context.cs]: Personally I don't like helper methods like this that as they don't really save anything and do exactly the same. Unline `StartPumpWithConcurrencySetToOne(1)` where it is not intuitive that 1 stands for concurrency. Even then it could be written as  `pump.Start(new PushRuntimeSettings(concurrency: 1));` and helper method would not be required.

File: src/Tests/Seam/When_dispatching_messages_in_receive_context.cs [hunk 3]
```diff
@@ -43,15 +43,15 @@ public void SetUp()
 
         async Task SetupAsync(TransportPartsContainer container, SettingsHolder settings)
         {
-            await TestUtility.Delete("sales", "myqueue");
+            await TestUtility.Delete("sales", TestQueueName);
```
Comment (SeanFeldman) [inline src/Tests/Seam/When_dispatching_messages_in_receive_context.cs]: We have two test queues: "sales" and "myqueue". Perhaps "sourceQueueName" and "destinationQueueName"?

File: src/Tests/Seam/When_dispatching_messages_in_receive_context.cs [hunk 4]
```diff
@@ -64,17 +65,14 @@ public void SetUp()
 
                 await pump.Init(async context =>
                 {
-                    // normally the core would do that
-                    context.Context.Set(context.TransportTransaction);
```
Comment (SeanFeldman) [inline src/Tests/Seam/When_dispatching_messages_in_receive_context.cs]: I recall we had to introduce it when core was developed 😄

**Comment by danielmarbach** [comment]
@Particular/azure-maintainers this is ready for reviewing

We addressed @SeanFeldman comments.

When this is good to go we will squash the current commits and then we can start reviewing #434 and pull those changes into the hotfix branch (this branch) is well.

**Comment by Scooletz** [comment]
Once we have this I'm ready to  #435 backport it to 7.1.0

**Comment by SeanFeldman** [comment]
Need to merge #434 first

**Comment by danielmarbach** [comment]
#434 has been merged. This is ready to go

**Comment by SeanFeldman** [comment]
merged
