### PR TITLE
Subscription fails on multiple namespaces

### LINKED ISSUE #487: Roundrobin strategy - 2 ASB namespaces with same subscription names
Hi,

I have 2 ASB namespaces. I have a topic called XX on each one of them. The names of the topics are same. I have a Azure worker role using NSB ASB 7.1.1 and uses round robin strategy. This worker role creates a subscription called YY to topic XX on namespace1 and another subscription called YY to topic XX on namespace2. Here the creation of  subscription YY on topic XX on namespace2 fails because of the following code.

var exists = await rememberExistence.GetOrAdd(key, notFoundKey =>
            {
                logger.InfoFormat("Checking namespace for existence of subscription '{0}' for the topic '{1}'", subscriptionName, topicPath);
                return namespaceClient.SubscriptionExists(topicPath, subscriptionName);
            }).ConfigureAwait(false);

The key here will always be the same since the topic name and subscription name are the same but they are in different namespaces.

### PR DESCRIPTION
**Pull request by boblangley**
Fixes #487 

## Who's affected

Anyone using Azure Service Bus transport and using a namespace partitioning strategy that creates the same subscription in multiple namespaces including the built-in strategies [Round Robin](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#round-robin-namespace-partitioning) and [Fail over](https://docs.particular.net/nservicebus/azure-service-bus/multiple-namespaces-support#fail-over-namespace-partitioning).

## Symptoms

When using multiple namespaces NServiceBus throws a `MessagingEntityNotFoundException` exception during startup.

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@boblangley after thinking about it, we probably should fix the key calculation for queues and topics. Since it's internal info, it won't affect services after upgrade.

Also, not to forget to update our logs to provide meaningful info.

**Comment by boblangley** [comment]
@SeanFeldman I added the namespace host name logging for subscription creators

I submitted unified key generation and namespace host logging separately for Topics and Queues in #491

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 1]
```diff
@@ -60,20 +60,20 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
                     };
 
                     await namespaceManager.CreateSubscription(subscriptionDescription, ruleDescription).ConfigureAwait(false);
-                    logger.Info($"Subscription '{subscriptionDescription.UserMetadata}' created as '{subscriptionDescription.Name}' with rule '{ruleDescription.Name}' for event '{meta.SubscribedEventFullName}'");
+                    logger.Info($"Subscription '{subscriptionDescription.UserMetadata}' created as '{subscriptionDescription.Name}' with rule '{ruleDescription.Name}' for event '{meta.SubscribedEventFullName}' in namespace {namespaceManager.Address.Host}");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: > in namespace {namespaceManager.Address.Host}

we single quote all the values but namespace. Should do that one as well.

Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: Period at the end of the sentence

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 2]
```diff
@@ -60,20 +60,20 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
...
 
-                    var key = subscriptionDescription.TopicPath + subscriptionDescription.Name;
+                    var key = GenerateSubscriptionKey(namespaceManager.Address, subscriptionDescription.TopicPath, subscriptionDescription.Name);
                     await rememberExistence.AddOrUpdate(key, keyNotFound => Task.FromResult(true), (updateTopicPath, previousValue) => Task.FromResult(true)).ConfigureAwait(false);
                 }
                 else
                 {
                     logger.Info($"Subscription '{subscriptionDescription.Name}' aka '{subscriptionDescription.UserMetadata}' already exists, skipping creation");
-                    logger.InfoFormat("Checking if subscription '{0}' needs to be updated", subscriptionDescription.Name);
+                    logger.InfoFormat("Checking if subscription '{0}' in namespace {1} needs to be updated", subscriptionDescription.Name, namespaceManager.Address.Host);
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 3]
```diff
@@ -60,20 +60,20 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
...
 
                     var existingSubscriptionDescription = await namespaceManager.GetSubscription(subscriptionDescription.TopicPath, subscriptionDescription.Name).ConfigureAwait(false);
                     if (MembersAreNotEqual(existingSubscriptionDescription, subscriptionDescription))
                     {
-                        logger.Info($"Updating subscription '{subscriptionDescription.Name}' with new description");
+                        logger.Info($"Updating subscription '{subscriptionDescription.Name}' in namespace {namespaceManager.Address.Host} with new description");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 4]
```diff
@@ -83,7 +83,7 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
                         Filter = new SqlFilter(sqlFilter),
                         Name = metadata.SubscriptionNameBasedOnEventWithNamespace
                     };
-                    logger.Info($"Adding subscription rule '{ruleDescription.Name}' for event '{meta.SubscribedEventFullName}'");
+                    logger.Info($"Adding subscription rule '{ruleDescription.Name}' for event '{meta.SubscribedEventFullName}' in namespace {namespaceManager.Address.Host}");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 5]
```diff
@@ -98,7 +98,7 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
             catch (MessagingEntityAlreadyExistsException)
             {
                 // the subscription already exists or another node beat us to it, which is ok
-                logger.Info($"Subscription '{subscriptionDescription.Name}' already exists, another node probably beat us to it");
+                logger.Info($"Subscription '{subscriptionDescription.Name}' in namespace {namespaceManager.Address.Host} already exists, another node probably beat us to it");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 6]
```diff
@@ -172,9 +172,9 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
 
         async Task<bool> ExistsAsync(string topicPath, string subscriptionName, string metadata, INamespaceManager namespaceClient, bool removeCacheEntry = false)
         {
-            logger.Info($"Checking existence cache for subscription '{subscriptionName}' aka '{metadata}'");
+            logger.Info($"Checking existence cache for subscription '{subscriptionName}' aka '{metadata}' in namespace {namespaceClient.Address.Host}");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 7]
```diff
@@ -184,11 +184,11 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
 
             var exists = await rememberExistence.GetOrAdd(key, notFoundKey =>
             {
-                logger.Info($"Checking namespace for existence of subscription '{subscriptionName}' for the topic '{topicPath}'");
+                logger.Info($"Checking namespace {namespaceClient.Address.Host} for existence of subscription '{subscriptionName}' for the topic '{topicPath}'");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

File: src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs [hunk 8]
```diff
@@ -184,11 +184,11 @@ public AzureServiceBusForwardingSubscriptionCreator(ReadOnlySettings settings)
...
                 return namespaceClient.SubscriptionExists(topicPath, subscriptionName);
             }).ConfigureAwait(false);
 
-            logger.Info($"Determined, from cache, that the subscription '{subscriptionName}' {(exists ? "exists" : "does not exist")}");
+            logger.Info($"Determined, from cache, that the subscription '{subscriptionName}' in namespace {namespaceClient.Address.Host} {(exists ? "exists" : "does not exist")}");
```
Comment (SeanFeldman) [inline src/Transport/Creation/AzureServiceBusForwardingSubscriptionCreator.cs]: same as above

**Comment by SeanFeldman** [comment]
This targets `master`... we need it to go to a hotfix.

**Comment by SeanFeldman** [comment]
build is red 😞

**Comment by boblangley** [comment]
On hold until 7.1.4 branch can be rebased.
