### PR TITLE
HierarchyComposition fixes

### LINKED ISSUE #190: Missing: HierarchyComposition - SetPathGenerator
It's not possible to configure this property yet

### LINKED ISSUE #222: Remove EntityType.EventHub
EventHub is not part of the messaging. 
Remove enum value [`EntityType.EventHub`](https://github.com/Particular/NServiceBus.AzureServiceBus/blob/5140f1add6d00dd069b7a0df29d0020b90dfc109/src/Transport/Topology/MetaModel/EntityType.cs#L8).

### PR DESCRIPTION
**Pull request by SeanFeldman**
`HierarchyComposition` should not be applied on entities of a rule type. Also, there was no way to set path generator, which rendered this strategy useless.

fixes #190 - allow to set path generator
fixes #222 - `EntityType.EventHub` is not used

### CODE REVIEW

**Comment by SeanFeldman** [comment]
@Particular/azure-service-bus-maintainers please review

File: src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs [hunk 1]
```diff
@@ -1,24 +1,36 @@
 namespace NServiceBus.AzureServiceBus.Addressing
 {
     using System;
+    using Settings;
 
     public class HierarchyComposition : ICompositionStrategy
     {
-        Func<string, string> pathGenerator;
+        internal const string PathGeneratorSettingsKey = "HierarchyComposition.PathGenerator";
```
Comment (yvesgoeleven) [inline src/Transport/Addressing/Composition/Strategies/HierarchyComposition.cs]: Any reason this is not in the WellKnowKeys class?

**Comment by SeanFeldman** [comment]
@yvesgoeleven done. Please review.
